AWSTemplateFormatVersion: '2010-09-09'
Description: StripeProtection lead capture infrastructure (S3 + DynamoDB)

Parameters:
  BucketName:
    Type: String
    Default: stripeprotection-leads
    Description: S3 bucket for lead storage
  DynamoTableName:
    Type: String
    Default: StripeProtectionLeads
    Description: DynamoDB table name for lead index

Resources:
  LogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  LeadsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LoggingConfiguration:
        DestinationBucketName: !Ref LogsBucket
        LogFilePrefix: logs/
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DraftRetention
            Status: Enabled
            Prefix: leads/draft/
            ExpirationInDays: 60
          - Id: FinalTransitions
            Status: Enabled
            Prefix: leads/final/
            Transitions:
              - StorageClass: STANDARD_IA
                TransitionInDays: 30
              - StorageClass: GLACIER
                TransitionInDays: 180

  LeadsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LeadsBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: EnforceTLS
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !Sub arn:aws:s3:::${BucketName}
              - !Sub arn:aws:s3:::${BucketName}/*
            Condition:
              Bool:
                aws:SecureTransport: false

  LeadsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DynamoTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: received_at
          AttributeType: S
        - AttributeName: email
          AttributeType: S
        - AttributeName: utm_source
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: byStatusDate
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: received_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: byEmail
          KeySchema:
            - AttributeName: email
              KeyType: HASH
            - AttributeName: received_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: byUtmSource
          KeySchema:
            - AttributeName: utm_source
              KeyType: HASH
            - AttributeName: received_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

Outputs:
  LeadsBucketName:
    Value: !Ref LeadsBucket
  LogsBucketName:
    Value: !Ref LogsBucket
  LeadsTableName:
    Value: !Ref LeadsTable
  GSIs:
    Value: "byStatusDate,byEmail,byUtmSource"

